### ISSUE TITLE
Concerns about vanguard + question

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#14]
Lovely project! Didn't find a way to conctact you so I'll do it here (its in the general interest anyway to know this)

The program only interacts with LCU for stats correct? so we should be in the clear regarding vanguard? no hooking is done into the actual process right?

Furthermore, I am planning on writing a plugin for obsidian to allow us to import our games into there and am requesting your permission to publish it.

**Comment by FFFFFFFXXXXXXX** [comment]
Thanks, I just added a public email to my github account so you can reach me that way (fffffffxxxxxxxfffffffxxxxxxx@gmail.com).

The program does currently not do any memory reading. It only interacts with the LCU API for the post game stats and the ingame API (https://localhost:2999) for the ingame-events.
Both will very likely remain unaffected by Vanguard since they can't really be used for cheating but I don't know for sure.

Currently Riots answer to inquiries regarding this is something like

> Hi there - due to the recent changes at Riot, we've been a bit delayed in getting this information. We're continuing to have internal conversations in this space and will provide an update as soon as we can.

and I fear I won't get a clear answer anytime soon because of the layoffs.

One thing that might potentially make problems with Vanguard is the video-recording method used. Currently I use libobs's [Game Capture Source](https://obsproject.com/kb/game-capture-source) which hooks into the games graphics rencdering (graphics-hook64.dll). But it's a 50/50 if that's going to be a problem since OBS / libobs is such a widely used software.  
Anyways, in case it is a problem I can just switch to another screen-recording method.

I don't mind you making an Obsidian plugin like that - not that I would have any legal (or moral) basis to stop you from doing that anyways.
I assume it's going to be something like an alternative interface for viewing the videos / stats?
Since I use Obsidian as well I am excited to try it whenever you are ready to publish it!

In case it helps - the typescript definition for the {videoname}.json files is in: <https://github.com/FFFFFFFXXXXXXX/league_record/blob/master/src/bindings.ts#L53>  
I could publish those as an npm package in case you or someone else needs them.

**Comment by ceselder** [comment]
Lovely! I'll let you know asap when the plugin is done!

It is indeed just an interface thing, where it will show you death clips with template on how to review them and improve etc

**Comment by FFFFFFFXXXXXXX** [comment]
The typescript bindings are now available: https://www.npmjs.com/package/@fffffffxxxxxxx/league_record_types

**Comment by ceselder** [comment]
https://github.com/ceselder/obsidian_league_record

Here's the link to the github repo of the obsidian plugin <3
