### ISSUE TITLE
[feature request] auto-delete old recordings

### ISSUE THREAD

**Issue by btvoidx** [FFFFFFFXXXXXXX/league_record#20]
By age, by total directory size, or both. Renamed videos should not be deleted, but I'm not sure how to check for it without introducing funky behaviour, so probably should add favourite/starring functionality too, and exclude those. (maybe even starring on rename automatically)

**Comment by ceselder** [comment]
seconding this. I would also love this feature.

How outplayed.tv approaches this is that you allocate X amount of space, and when you reach the limit specified, the old recordings start to be deleted in order to make space for it.

"Not deleting renamed videos" seems like a janky way to say "we should probably have a favoriting system so that the game appears at the top of the list and is not deleted" but its up to the dev to conclude if this is feature creep or not.

I have never programmed in rust, but am a somewhat experienced web developer, if the dev doesnt feel like it I might try my hand at rust haha 👀

**Comment by btvoidx** [comment]
I think a good que for cleanup is recording end. That way total size may still exceed a set limit, but only while a game is being recorded.

For even more accurate size control you could trigger a cleanup whenever writing more data to disk would exceed the limit, and continue writing only after in completes. Although this may memory usage may spike, depending on how long the cleanup takes.

**Comment by ceselder** [comment]
> I have an implementation of this feature in [9ef514d](https://github.com/FFFFFFFXXXXXXX/league_record/commit/9ef514d2c9e4932ca7f227e65e97ea8e5386f433).
> 
> The "cleanup" currently only runs once when starting the app. I still have to think about if I want to run the cleanup more often than that. Maybe before a game gets recorded?
> 
> This will be in the next release, when I finish the feature to mark recordings as "favorites" that dont get deleted.

I'm not gonna lie, I dont think im the only one that boots up their pc and then plays league all day and doesn't have **that** much drive space left.

**Comment by FFFFFFFXXXXXXX** [comment]
Alright the pre-release for this feature is out. https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.19.0.
Usually I test this for a week myself before I release it, but since I currently don't have much time to play league I thought I would release it as a pre-release if you want to try it.

**Comment by FFFFFFFXXXXXXX** [comment]
implemented in v1.19.0
