### ISSUE TITLE
auto updating

### ISSUE THREAD

**Issue by judehek** [FFFFFFFXXXXXXX/league_record#25]
hey- obviously incredibly grateful for the countless hours you've put into this project

feel free to shoot this down if it would be too much, was wondering if you've considered auto updating? not sure how difficult it would be, but would be nice to not have to download for every fix. 

again totally get it if there's no simple way- don't want you to have to pay to host the updates or anything

thanks again!

**Comment by FFFFFFFXXXXXXX** [comment]
It's been on my backlog for a while and I have a super simple implementation of an auto-updater in [this](https://github.com/FFFFFFFXXXXXXX/league_record/tree/updater) branch.

I still have to figure out some stuff on how to properly release the updates but it should be doable - it will just take me a bit.
But I don't plan an releasing any new releases in the near future anyways (unless Riot breaks something 🥲) because there is not much to do and the current version is pretty stable.

**Comment by judehek** [comment]
awesome, thanks as always!
