### ISSUE TITLE
Ultrawide support

### ISSUE THREAD

**Issue by BigBoyBarney** [FFFFFFFXXXXXXX/league_record#7]
Hey! I love the app, as it streamlines league recording a lot. Much easier than manually recording every time with OBS, so thank you for that!!

Would it be possible to add ultrawide (43:18) recording support? Currently, the recording is compressed to 16:9, which looks quite funny, and it won't detect the in game events properly either, which I assume is tied to how it is recorded.

Thank you in advance!

**Comment by FFFFFFFXXXXXXX** [comment]
Hmm, I'll see what I can do.
What is your exact resolution - 3440x1440?

Also what do you mean by "it won't detect the in game events properly"? Do they not get recorded at all?

**Comment by FFFFFFFXXXXXXX** [comment]
Alright I have a pre-release (https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.14.3) that adds support for different aspect ratios.
If you want to try it out you have to delete "outputResolution" from your settings. Only then automatic aspect ratio detection is used. Alternatively you could explicitly set `"outputResolution": "2580x1080p"` or `"outputResolution": "3440x1440p"`.

---

Also regarding the ingame information collection not working.
There is a rare windows bug (feature?) where windows stops the ingame API from starting which makes it impossible to collect the ingame data. A reboot of the PC usually fixes it. Extensively described here: [stackoverflow](https://stackoverflow.com/questions/58216537/what-is-administered-port-exclusions-in-windows-10/65234135#65234135)

In case the ingame data collection fails agains you can check if this is the reason by running `netsh interface ipv4 show excludedportrange protocol=tcp`
This should give you a list of "blocked/reserved" port ranges (from - to):

```
Startport      Endport
----------    --------
      5357        5357
     50000       50059     *
     54896       54995
     54996       55095
     55096       55195
     55196       55295
     55296       55395
     55396       55495
     55496       55595
     55596       55695
     55696       55795
     55796       55895
``` 

If the port `2999` is in one of these ranges, then you are encountering the problem linked above.
The fix is to get rid of the "reserved" ports by restarting your PC or trying the things from the stackoverflow answer and then running `netsh int ipv4 add excludedportrange protocol=tcp startport=2999 numberofports=1` as administrator.

Since it's a weird windows thing there is nothing else I can do to work around that.

**Comment by FFFFFFFXXXXXXX** [comment]
[Release v1.15.1](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.15.1) is out now so I'll close this issue for now.
